version: "3"

services:
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - ".env"
    volumes:
      - wordpress:/var/www/html
    networks:
      - my-network

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    networks:
      - my-network

  mariadb:
    build : ./requirements/mariadb
    container_name: mariadb
    env_file:
      - ".env"
    volumes:
      - db:/var/lib/mysql
    networks:
      - my-network

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wp
  db: 
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/db
networks:
  my-network:
    driver: bridge
